### ISSUE TITLE
LICENSE file installation in /usr/local/ ?

### ISSUE THREAD

**Issue by juanmirocks** [eflglobal/filters#29]
Is it expected that `pip install filters` requires writing the `LICENSE` file (at least macOS) in `/usr/local/LICENSE` ?

Somehow naturally, in my system I need root access to write a filter under `/usr/local/`, therefore the installation fails.

It seems to me strange writing a file in that folder.

Full stack:

```python
Collecting filters
  Using cached filters-1.2.3-py3-none-any.whl
Requirement already up-to-date: python-dateutil in /usr/local/lib/python3.6/site-packages (from filters)
Requirement already up-to-date: pytz in /usr/local/lib/python3.6/site-packages (from filters)
Requirement already up-to-date: regex in /usr/local/lib/python3.6/site-packages (from filters)
Requirement already up-to-date: six in /usr/local/lib/python3.6/site-packages (from filters)
Installing collected packages: filters
Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/lib/python3.6/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/usr/local/lib/python3.6/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/usr/local/lib/python3.6/site-packages/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/usr/local/lib/python3.6/site-packages/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/usr/local/lib/python3.6/site-packages/pip/wheel.py", line 377, in move_wheel_files
    clobber(source, dest, False, fixer=fixer, filter=filter)
  File "/usr/local/lib/python3.6/site-packages/pip/wheel.py", line 323, in clobber
    shutil.copyfile(srcfile, destfile)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/shutil.py", line 121, in copyfile
    with open(dst, 'wb') as fdst:
PermissionError: [Errno 13] Permission denied: '/usr/local/LICENSE'
```

**Comment by todofixthis** [comment]
Hey Juan.  Thanks for the heads-up!

It looks like you might be trying to install the library globally (into `/usr/local/lib/python3.6/site-packages`).  I have to admit, we never tested the library this way.

Is it feasible to install the library into a virtualenv?

You can do a quick test like this:
```
# Install virtualenvwrapper.
sudo pip install virtualenvwrapper
source /usr/local/bin/virtualenvwrapper.sh

# Create a temporary virtualenv.
mkvirtualenv

# Try installing the library.
pip install filters

# Delete the temp virtualenv when finished.
deactivate
```

I'll look into why setuptools is trying to install the license file in a weird place, but hopefully using a virtualenv will help you work around the issue for now!

**Comment by juanmirocks** [comment]
Sure, thanks! Yes, a virtualenv will do. Nonetheless, I guess some users
may install your library globally :)

Thanks again

**Comment by todofixthis** [comment]
Hey Juan!  v1.3.0 was just released, and it potentially contains a fix for this issue.  When you have a chance, could you verify if this issue is still reproducible?
